version: "3.3"
services:
  janus:
    image: htmlcoin/janus:dev
    build:
      context: ../../
      dockerfile: ./Dockerfile
      cache_from:
        - golang:3.16-alpine
        - htmlcoin/janus:dev
    ports:
      - "24889:24889"
    environment:
      - HTMLCOIN_RPC=http://htmlcoin:testpasswd@htmlcoin:4889
    volumes:
      - ../../:/src:ro
    depends_on:
      - htmlcoin
    command: --bind 0.0.0.0 --accounts /src/myaccounts.txt --dev
  htmlcoin:
    ports:
      - "4889:4889"
    image: htmlcoin/htmlcoin-seeded
    build:
      context: ../../docker
      dockerfile: ./htmlcoin-seeded.Dockerfile
      cache_from:
        - htmlcoin/htmlcoin-seeded
    container_name: htmlcoin_seeded_testchain
    command: htmlcoind -regtest -addrindex -txindex -rpcbind=0.0.0.0:4889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=htmlcoin -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
  openzeppelin:
    image: htmlcoin/janus-openzeppelin
    build:
      context: .
      dockerfile: ./openzeppelin.Dockerfile
      cache_from:
        - htmlcoin/janus-openzeppelin
    environment:
      - GENERATE_TO_ADDRESS=qW28njWueNpBXYWj2KDmtFG2gbLeALeHfV
    depends_on:
      - janus
    command: truffle test --network docker
